services:
  - type: web
    name: staredu-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
    healthCheckPath: /health
